language: scala
jdk: openjdk8
script:
- git clone -b 2.12.x https://github.com/scala/scala
- sbt -Dfile.encoding=UTF-8 "runMain MakeReleaseNotes 2.12.0 2.12.1 2345/06/07 `pwd`/scala"
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
